### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by sah-anshu** [CapacitorSet/hotspot#1]
pi@raspberrypi:~/hotspot $ sudo node createinstaller.js
module.js:538
    throw err;
    ^

Error: Cannot find module '/home/pi/hotspot/createinstaller.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
pi@raspberrypi:~/hotspot $

**Comment by CapacitorSet** [comment]
There's a typo in the readme, it should be `createInstaller`.

Anyway, it's an old project that I had made for myself, so some things may need tweaking to work elsewhere.
